SET NAMES utf8mb4;

DROP TABLE IF EXISTS `asset_category`;
CREATE TABLE `asset_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `category_code` VARCHAR(255) NULL,
  `category_name` VARCHAR(255) NULL,
  `parent_id` BIGINT NULL,
  `level` BIGINT NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `asset_goods`;
CREATE TABLE `asset_goods` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `goods_code` VARCHAR(255) NULL,
  `goods_name` VARCHAR(255) NULL,
  `asset_category_code` VARCHAR(255) NULL,
  `asset_category_name` VARCHAR(255) NULL,
  `asset_model` VARCHAR(255) NULL,
  `asset_unit` VARCHAR(255) NULL,
  `manufacturer` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `residual_value_rate` DECIMAL(24,6) NULL,
  `inventory_lower_limit` DECIMAL(24,6) NULL,
  `inventory_limit` DECIMAL(24,6) NULL,
  `is_join_asset` VARCHAR(255) NULL,
  `asset_icon` VARCHAR(255) NULL,
  `asset_file` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `store_address` VARCHAR(255) NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `asset_info`;
CREATE TABLE `asset_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_id` BIGINT NULL,
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `in_warehousing_id` BIGINT NULL,
  `warehousing_entry_code` VARCHAR(255) NULL,
  `warehousing_entry_name` VARCHAR(255) NULL,
  `asset_code` VARCHAR(255) NULL,
  `asset_name` VARCHAR(255) NULL,
  `asset_category_code` VARCHAR(255) NULL,
  `asset_category_name` VARCHAR(255) NULL,
  `asset_model` VARCHAR(255) NULL,
  `asset_unit` VARCHAR(255) NULL,
  `manufacturer` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `serial_number` VARCHAR(255) NULL,
  `asset_status_code` VARCHAR(255) NULL,
  `asset_status_name` VARCHAR(255) NULL,
  `asset_source_code` VARCHAR(255) NULL,
  `asset_source_name` VARCHAR(255) NULL,
  `purchase_date` DATETIME NULL,
  `purchase_price` DECIMAL(24,6) NULL,
  `date_of_production` DATETIME NULL,
  `admin_company_id` VARCHAR(255) NULL,
  `admin_company_name` VARCHAR(255) NULL,
  `admin_dept_id` VARCHAR(255) NULL,
  `admin_dept_name` VARCHAR(255) NULL,
  `admin_manager_id` VARCHAR(255) NULL,
  `admin_manager_name` VARCHAR(255) NULL,
  `use_company_id` VARCHAR(255) NULL,
  `use_company_name` VARCHAR(255) NULL,
  `use_dept_id` VARCHAR(255) NULL,
  `use_dept_name` VARCHAR(255) NULL,
  `use_account_id` VARCHAR(255) NULL,
  `use_account_name` VARCHAR(255) NULL,
  `wms_store_code` VARCHAR(255) NULL,
  `wms_store_name` VARCHAR(255) NULL,
  `residual_value_rate` DECIMAL(24,6) NULL,
  `asset_icon` VARCHAR(255) NULL,
  `asset_file` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `store_address` VARCHAR(255) NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `asset_life_time`;
CREATE TABLE `asset_life_time` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `asset_id` BIGINT NULL,
  `asset_code` VARCHAR(255) NULL,
  `asset_name` VARCHAR(255) NULL,
  `asset_milestone` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `store_address` VARCHAR(255) NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_goods_common_operation_order`;
CREATE TABLE `wms_goods_common_operation_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_id` BIGINT NULL,
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `in_warehousing_id` BIGINT NULL,
  `warehousing_entry_code` VARCHAR(255) NULL,
  `warehousing_entry_name` VARCHAR(255) NULL,
  `common_operation_date` DATETIME NULL,
  `common_operation_desc` VARCHAR(255) NULL,
  `common_operation_file` VARCHAR(255) NULL,
  `stock_return_total_data` DECIMAL(24,6) NULL,
  `common_operation_total_amount` DECIMAL(24,6) NULL,
  `company_id` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `dept_id` VARCHAR(255) NULL,
  `dept_name` VARCHAR(255) NULL,
  `user_id` VARCHAR(255) NULL,
  `user_name` VARCHAR(255) NULL,
  `expect_return_date` DATETIME NULL,
  `transfer_company_id` VARCHAR(255) NULL,
  `transfer_company_name` VARCHAR(255) NULL,
  `transfer_dept_id` VARCHAR(255) NULL,
  `transfer_dept_name` VARCHAR(255) NULL,
  `process_instance_id` VARCHAR(255) NULL,
  `process_status` INT NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_goods_warehousing_detail`;
CREATE TABLE `wms_goods_warehousing_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_id` BIGINT NULL,
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `common_operation_id` BIGINT NULL,
  `common_operation_code` VARCHAR(255) NULL,
  `common_operation_name` VARCHAR(255) NULL,
  `common_operation_type` VARCHAR(255) NULL,
  `asset_id` BIGINT NULL,
  `asset_code` VARCHAR(255) NULL,
  `asset_name` VARCHAR(255) NULL,
  `asset_category_code` VARCHAR(255) NULL,
  `asset_category_name` VARCHAR(255) NULL,
  `asset_model` VARCHAR(255) NULL,
  `asset_unit` VARCHAR(255) NULL,
  `manufacturer` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `serial_number` VARCHAR(255) NULL,
  `asset_status_code` VARCHAR(255) NULL,
  `asset_status_name` VARCHAR(255) NULL,
  `asset_source_code` VARCHAR(255) NULL,
  `asset_source_name` VARCHAR(255) NULL,
  `purchase_date` DATETIME NULL,
  `purchase_price` DECIMAL(24,6) NULL,
  `date_of_production` DATETIME NULL,
  `admin_company_id` VARCHAR(255) NULL,
  `admin_company_name` VARCHAR(255) NULL,
  `admin_dept_id` VARCHAR(255) NULL,
  `admin_dept_name` VARCHAR(255) NULL,
  `admin_manager_id` VARCHAR(255) NULL,
  `admin_manager_name` VARCHAR(255) NULL,
  `wms_store_code` VARCHAR(255) NULL,
  `wms_store_name` VARCHAR(255) NULL,
  `residual_value_rate` DECIMAL(24,6) NULL,
  `use_company_id` VARCHAR(255) NULL,
  `use_company_name` VARCHAR(255) NULL,
  `use_dept_id` VARCHAR(255) NULL,
  `use_dept_name` VARCHAR(255) NULL,
  `use_account_id` VARCHAR(255) NULL,
  `use_account_name` VARCHAR(255) NULL,
  `transfer_use_dept_id` VARCHAR(255) NULL,
  `transfer_use_dept_name` VARCHAR(255) NULL,
  `transfer_use_account_id` VARCHAR(255) NULL,
  `transfer_use_account_name` VARCHAR(255) NULL,
  `asset_icon` VARCHAR(255) NULL,
  `asset_file` VARCHAR(255) NULL,
  `is_join_asset` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `store_address` VARCHAR(255) NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_purchase_in_warehousing`;
CREATE TABLE `wms_purchase_in_warehousing` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_id` BIGINT NULL,
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `warehousing_entry_code` VARCHAR(255) NULL,
  `warehousing_entry_name` VARCHAR(255) NULL,
  `in_warehousing_date` DATETIME NULL,
  `in_warehousing_desc` VARCHAR(255) NULL,
  `in_warehousing_file` VARCHAR(255) NULL,
  `in_warehousing_total_data` DECIMAL(24,6) NULL,
  `in_warehousing_total_amount` DECIMAL(24,6) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_purchase_order`;
CREATE TABLE `wms_purchase_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `applicant_date` DATETIME NULL,
  `company_id` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `applicant_dept_id` VARCHAR(255) NULL,
  `applicant_dept_name` VARCHAR(255) NULL,
  `applicant_user_id` VARCHAR(255) NULL,
  `applicant_user_name` VARCHAR(255) NULL,
  `supplier_code` VARCHAR(255) NULL,
  `supplier_name` VARCHAR(255) NULL,
  `applicant_desc` VARCHAR(255) NULL,
  `purchase_order_file` VARCHAR(255) NULL,
  `purchase_order_total_data` DECIMAL(24,6) NULL,
  `purchase_order_total_amount` DECIMAL(24,6) NULL,
  `process_instance_id` VARCHAR(255) NULL,
  `process_status` INT NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_purchase_order_detail`;
CREATE TABLE `wms_purchase_order_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `purchase_order_id` VARCHAR(255) NULL,
  `purchase_order_code` VARCHAR(255) NULL,
  `purchase_order_name` VARCHAR(255) NULL,
  `category_code` VARCHAR(255) NULL,
  `category_name` VARCHAR(255) NULL,
  `goods_code` VARCHAR(255) NULL,
  `goods_name` VARCHAR(255) NULL,
  `purchase_price` DECIMAL(24,6) NULL,
  `purchase_num` DECIMAL(24,6) NULL,
  `purchase_total_amonut` DECIMAL(24,6) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `wms_warehousing`;
CREATE TABLE `wms_warehousing` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `warehousing_code` VARCHAR(255) NULL,
  `warehousing_name` VARCHAR(255) NULL,
  `parent_id` BIGINT NULL,
  `level` BIGINT NULL,
  `warehousing_category_code` VARCHAR(255) NULL,
  `warehousing_category_name` VARCHAR(255) NULL,
  `warehousing_address` VARCHAR(255) NULL,
  `company_id` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `sort` INT NULL,
  `status` INT NULL,
  `remark` VARCHAR(255) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` VARCHAR(64) NULL DEFAULT '' COMMENT '创建者',
  `updater` VARCHAR(64) NULL DEFAULT '' COMMENT '更新者',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

